output to terminal and csv split

diff --git a/fetchstats b/fetchstats
--- a/fetchstats
+++ b/fetchstats
@@ -6,11 +6,11 @@
 # Richard Crowley <richard@opendns.com>
 #
 
-CSVURL="https://dashboard.opendns.com"
+RAWDATAURL="https://dashboard.opendns.com"
 LOGINURL="https://login.opendns.com/?source=dashboard"
 
 usage() {
-	echo "Usage: $0 <username> <network_id> <YYYY-MM-DD> [<YYYY-MM-DD>]" >&2
+	echo "Usage: $0 <username> <network_id> <YYYY-MM-DD> [<YYYY-MM-DD>] <output_file>" >&2
 	exit 1
 }
 
@@ -32,10 +32,18 @@ if [ -z "$NETWORK_ID" ] ; then usage ; fi
 date_check "$3"
 if [ -z "$4" ] ; then
 	DATE="$3"
+	OUTPUT_FILE="$5"
 else
 	date_check "$4"
 	DATE="$3to$4"
+	OUTPUT_FILE="$5"
 fi
+
+if [ -z "$OUTPUT_FILE" ] ; then usage ; fi
+
+# Clear the output file at the start
+> "$OUTPUT_FILE"
+echo "Output will also be saved to $OUTPUT_FILE"
 
 echo -n "Password for $USERNAME: " >&2
 stty -echo
@@ -77,10 +85,13 @@ fi
 GO="yes"
 PAGE=1
 while [ "yes" == "$GO" ] ; do
+	echo "Fetching page $PAGE..."
+
 	RAW=`curl --silent --insecure \
 		--cookie "$COOKIEJAR" \
-		"$CSVURL/stats/$NETWORK_ID/topdomains/$DATE/page$PAGE.csv" \
+		"$RAWDATAURL/stats/$NETWORK_ID/topdomains/$DATE/page$PAGE.csv" \
 	`
+	
 	if [ "$PAGE" == "1" ]; then
 		if [ "$RAW" == "" ]; then
 			echo "You can not access $NETWORK_ID" >&2
@@ -88,17 +99,22 @@ while [ "yes" == "$GO" ] ; do
 		fi
 		HEADING=`echo "$RAW" | head -n 1`
 		if [[ "$HEADING" == *DOCTYPE* ]]; then
-		    echo "Error retrieving data.  Date range may be outside of available data." >&2
+		    echo "Error retrieving data. Date range may be outside of available data." >&2
 	        exit 2
 		fi
 	else
 		RAW=`echo "$RAW" | tail -n +2`
 	fi
 
-	if [ -z "$RAW" ] ; then GO="no"
-	else echo "$RAW" ; fi
+	if [ -z "$RAW" ] ; then 
+		echo "No more data at page $PAGE."
+		GO="no"
+	else 
+		echo "$RAW" >> "$OUTPUT_FILE"
+	fi
+
 	PAGE=$(($PAGE + 1))
 done
 
+echo "Finished fetching all pages."
 rm -f "$COOKIEJAR"
-
